.base_ruff_image:
  stage: build

  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # RUN QUALITY JOB IN PIPELINE ON THE DEFAULT BRANCH(BUT NOT IN OTHER BRANCH)

  interruptible: true
  image:
    name: ghcr.io/astral-sh/ruff:0.11.8-alpine

  before_script:
    - cd $CI_PROJECT_DIR
    - ls -la
    - ruff --version


Ruff Check:
  extends: .base_ruff_image
  script:
    - ruff check --output-format=gitlab > code-quality-report.json
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/code-quality-report.json

Ruff Format:
  extends: .base_ruff_image
  script:
    - ruff format --diff