line-length = 120
show-fixes = true
exclude = [".venv", ".gitlab-ci.yml"]

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-print
    "T20"
]
ignore = ["B026"]

