name: ci-release.yml
permissions:
  contents: write
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'pyproject.toml' # Ignore les modifications de ce fichier pour éviter les boucles
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore: bump version')" # Ignore les commits de version

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi

      - name: Extraire la version du tag
        id: extract_tag
        run: echo "tag_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Mettre à jour la version Poetry
        run: poetry version ${{ steps.extract_tag.outputs.tag_version }}

      - name: Récupérer la branche source du tag
        id: get_branch
        run: |
          branch=$(git for-each-ref --format='%(refname:short)' $(git show-ref -s --head HEAD) | grep -v HEAD | head -n1)
          echo "branch_name=${branch}" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ steps.get_branch.outputs.branch_name }}
          git add pyproject.toml
          git commit -m "chore: bump version to ${{ steps.extract_tag.outputs.tag_version }}" || echo "No changes to commit"
          git push origin ${{ steps.get_branch.outputs.branch_name }}


      - name: Build Package
        run: poetry build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}